### ISSUE TITLE
[Crash] Crashes when breaking controller block with shaders

### ISSUE THREAD

**Issue by mav-8** [SuperMartijn642/MovingElevators#114]
I'm trying to create a modpack but the mod doesn't seem to work with shaders. Is it incompatible? When I turn shaders off, it works as intended but as soon as I turn it on and break a controller block, the game crashes. I updated OptiFine and downloaded the latest dependencies for 1.18.1.

**Version Info**
- Minecraft, 1.18.1
- Moving Elevators, 1.3.5

**Are you using OptiFine?**: Yes

**Steps to Reproduce**
-Load OptiFine shaders
-Place down controller block
-Break controller block

**Crash report (~/logs/latest.log)**
Time: 3/27/22, 6:12 PM
Description: Rendering Block Entity

java.lang.NullPointerException: Rendering Block Entity
	at java.util.Objects.requireNonNull(Objects.java:208) ~[?:?] {re:mixin}
	at java.util.Optional.of(Optional.java:113) ~[?:?] {re:mixin}
	at net.minecraftforge.common.util.LazyOptional.map(LazyOptional.java:195) ~[forge-1.18.1-39.1.0-universal.jar%23165!/:?] {re:mixin,re:classloading}
	at com.supermartijn642.movingelevators.blocks.ControllerBlockEntity.getGroup(ControllerBlockEntity.java:117) ~[movingelevators-1.3.4-mc1.18.jar%23125!/:?] {re:classloading}
	at com.supermartijn642.movingelevators.blocks.ElevatorInputBlockEntityRenderer.render(ElevatorInputBlockEntityRenderer.java:38) ~[movingelevators-1.3.4-mc1.18.jar%23125!/:?] {re:classloading}
	at com.supermartijn642.movingelevators.blocks.ElevatorInputBlockEntityRenderer.m_6922_(ElevatorInputBlockEntityRenderer.java:19) ~[movingelevators-1.3.4-mc1.18.jar%23125!/:?] {re:classloading}
	at net.minecraft.client.renderer.blockentity.BlockEntityRenderDispatcher.m_112284_(BlockEntityRenderDispatcher.java:106) ~[client-1.18.1-20211210.034407-srg.jar%23161!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:entityculling.mixins.json:BlockEntityRenderDispatcherMixin,pl:mixin:APP:supplementaries.mixins.json:BlockEntityRendererDispatcher,pl:mixin:A}
	at net.minecraft.client.renderer.blockentity.BlockEntityRenderDispatcher.lambda$renderTileEntity$0(BlockEntityRenderDispatcher.java:79) ~[client-1.18.1-20211210.034407-srg.jar%23161!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:entityculling.mixins.json:BlockEntityRenderDispatcherMixin,pl:mixin:APP:supplementaries.mixins.json:BlockEntityRendererDispatcher,pl:mixin:A}
	at net.minecraft.client.renderer.blockentity.BlockEntityRenderDispatcher.m_112278_(BlockEntityRenderDispatcher.java:152) ~[client-1.18.1-20211210.034407-srg.jar%23161!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:entityculling.mixins.json:BlockEntityRenderDispatcherMixin,pl:mixin:APP:supplementaries.mixins.json:BlockEntityRendererDispatcher,pl:mixin:A}
	at net.minecraft.client.renderer.blockentity.BlockEntityRenderDispatcher.m_112267_(BlockEntityRenderDispatcher.java:77) ~[client-1.18.1-20211210.034407-srg.jar%23161!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:entityculling.mixins.json:BlockEntityRenderDispatcherMixin,pl:mixin:APP:supplementaries.mixins.json:BlockEntityRendererDispatcher,pl:mixin:A}
	at net.optifine.shaders.ShadersRender.renderShadowMap(ShadersRender.java:550) ~[OptiFine_1.18.1_HD_U_H6.jar%23166!/:?] {re:classloading}
	at net.optifine.shaders.Shaders.beginRender(Shaders.java:4976) ~[OptiFine_1.18.1_HD_U_H6.jar%23166!/:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1468) ~[client-1.18.1-20211210.034407-srg.jar%23161!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:A}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:1156) ~[client-1.18.1-20211210.034407-srg.jar%23161!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1041) ~[client-1.18.1-20211210.034407-srg.jar%23161!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:betterthirdperson.mixins.json:MinecraftMixin,pl:mixin:APP:fallingleaves.mixins.json:MinecraftClientMixin,pl:mixin:APP:mixins.ipnext.json:MixinMinecraftClient,pl:mixin:APP:terrablender_forge.mixins.json:client.MixinMinecraft,pl:mixin:APP:securitycraft.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:661) ~[client-1.18.1-20211210.034407-srg.jar%23161!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:betterthirdperson.mixins.json:MinecraftMixin,pl:mixin:APP:fallingleaves.mixins.json:MinecraftClientMixin,pl:mixin:APP:mixins.ipnext.json:MixinMinecraftClient,pl:mixin:APP:terrablender_forge.mixins.json:client.MixinMinecraft,pl:mixin:APP:securitycraft.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.1-20211210.034407-srg.jar%23161!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.18.1-39.1.0.jar%2323!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.util.Objects.requireNonNull(Objects.java:208) ~[?:?] {re:mixin}
	at java.util.Optional.of(Optional.java:113) ~[?:?] {re:mixin}
	at net.minecraftforge.common.util.LazyOptional.map(LazyOptional.java:195) ~[forge-1.18.1-39.1.0-universal.jar%23165!/:?] {re:mixin,re:classloading}
	at com.supermartijn642.movingelevators.blocks.ControllerBlockEntity.getGroup(ControllerBlockEntity.java:117) ~[movingelevators-1.3.4-mc1.18.jar%23125!/:?] {re:classloading}
	at com.supermartijn642.movingelevators.blocks.ElevatorInputBlockEntityRenderer.render(ElevatorInputBlockEntityRenderer.java:38) ~[movingelevators-1.3.4-mc1.18.jar%23125!/:?] {re:classloading}
	at com.supermartijn642.movingelevators.blocks.ElevatorInputBlockEntityRenderer.m_6922_(ElevatorInputBlockEntityRenderer.java:19) ~[movingelevators-1.3.4-mc1.18.jar%23125!/:?] {re:classloading}
	at net.minecraft.client.renderer.blockentity.BlockEntityRenderDispatcher.m_112284_(BlockEntityRenderDispatcher.java:106) ~[client-1.18.1-20211210.034407-srg.jar%23161!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:entityculling.mixins.json:BlockEntityRenderDispatcherMixin,pl:mixin:APP:supplementaries.mixins.json:BlockEntityRendererDispatcher,pl:mixin:A}
	at net.minecraft.client.renderer.blockentity.BlockEntityRenderDispatcher.lambda$renderTileEntity$0(BlockEntityRenderDispatcher.java:79) ~[client-1.18.1-20211210.034407-srg.jar%23161!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:entityculling.mixins.json:BlockEntityRenderDispatcherMixin,pl:mixin:APP:supplementaries.mixins.json:BlockEntityRendererDispatcher,pl:mixin:A}
	at net.minecraft.client.renderer.blockentity.BlockEntityRenderDispatcher.m_112278_(BlockEntityRenderDispatcher.java:152) ~[client-1.18.1-20211210.034407-srg.jar%23161!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:entityculling.mixins.json:BlockEntityRenderDispatcherMixin,pl:mixin:APP:supplementaries.mixins.json:BlockEntityRendererDispatcher,pl:mixin:A}
	at net.minecraft.client.renderer.blockentity.BlockEntityRenderDispatcher.m_112267_(BlockEntityRenderDispatcher.java:77) ~[client-1.18.1-20211210.034407-srg.jar%23161!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:entityculling.mixins.json:BlockEntityRenderDispatcherMixin,pl:mixin:APP:supplementaries.mixins.json:BlockEntityRendererDispatcher,pl:mixin:A}
	at net.optifine.shaders.ShadersRender.renderShadowMap(ShadersRender.java:550) ~[OptiFine_1.18.1_HD_U_H6.jar%23166!/:?] {re:classloading}
	at net.optifine.shaders.Shaders.beginRender(Shaders.java:4976) ~[OptiFine_1.18.1_HD_U_H6.jar%23166!/:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1468) ~[client-1.18.1-20211210.034407-srg.jar%23161!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:A}
-- Block Entity Details --
Details:
	Name: movingelevators:elevator_tile // com.supermartijn642.movingelevators.blocks.ControllerBlockEntity
	Block: Block{movingelevators:elevator_block}[facing=north]
	Block location: World: (-8,69,-8), Section: (at 8,5,8 in -1,4,-1; chunk contains blocks -16,-64,-16 to -1,319,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Block: Block{minecraft:air}
	Block location: World: (-8,69,-8), Section: (at 8,5,8 in -1,4,-1; chunk contains blocks -16,-64,-16 to -1,319,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
Stacktrace:
	at net.minecraft.client.renderer.blockentity.BlockEntityRenderDispatcher.m_112278_(BlockEntityRenderDispatcher.java:152) ~[client-1.18.1-20211210.034407-srg.jar%23161!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:entityculling.mixins.json:BlockEntityRenderDispatcherMixin,pl:mixin:APP:supplementaries.mixins.json:BlockEntityRendererDispatcher,pl:mixin:A}
	at net.minecraft.client.renderer.blockentity.BlockEntityRenderDispatcher.m_112267_(BlockEntityRenderDispatcher.java:77) ~[client-1.18.1-20211210.034407-srg.jar%23161!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:entityculling.mixins.json:BlockEntityRenderDispatcherMixin,pl:mixin:APP:supplementaries.mixins.json:BlockEntityRendererDispatcher,pl:mixin:A}
	at net.optifine.shaders.ShadersRender.renderShadowMap(ShadersRender.java:550) ~[OptiFine_1.18.1_HD_U_H6.jar%23166!/:?] {re:classloading}
	at net.optifine.shaders.Shaders.beginRender(Shaders.java:4976) ~[OptiFine_1.18.1_HD_U_H6.jar%23166!/:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1468) ~[client-1.18.1-20211210.034407-srg.jar%23161!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:A}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:1156) ~[client-1.18.1-20211210.034407-srg.jar%23161!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1041) ~[client-1.18.1-20211210.034407-srg.jar%23161!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:betterthirdperson.mixins.json:MinecraftMixin,pl:mixin:APP:fallingleaves.mixins.json:MinecraftClientMixin,pl:mixin:APP:mixins.ipnext.json:MixinMinecraftClient,pl:mixin:APP:terrablender_forge.mixins.json:client.MixinMinecraft,pl:mixin:APP:securitycraft.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:661) ~[client-1.18.1-20211210.034407-srg.jar%23161!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:betterthirdperson.mixins.json:MinecraftMixin,pl:mixin:APP:fallingleaves.mixins.json:MinecraftClientMixin,pl:mixin:APP:mixins.ipnext.json:MixinMinecraftClient,pl:mixin:APP:terrablender_forge.mixins.json:client.MixinMinecraft,pl:mixin:APP:securitycraft.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.1-20211210.034407-srg.jar%23161!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.18.1-39.1.0.jar%2323!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}

-- Affected level --
Details:
	All players: 1 total; [LocalPlayer['baenate'/112, l='ClientLevel', x=-9.27, y=69.00, z=-10.00]]
	Chunk stats: 5041, 319
	Level dimension: minecraft:overworld
	Level spawn location: World: (-32,87,0), Section: (at 0,7,0 in -2,5,0; chunk contains blocks -32,-64,0 to -17,319,15), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Level time: 4003 game time, 4003 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.ClientLevel.m_6026_(ClientLevel.java:517) ~[client-1.18.1-20211210.034407-srg.jar%23161!/:?] {re:mixin,xf:OptiFine:default,xf:fml:xaeroworldmap:xaero_wm_clientworldclass,xf:fml:xaerominimap:xaero_clientworldclass,re:classloading,xf:OptiFine:default,xf:fml:xaeroworldmap:xaero_wm_clientworldclass,xf:fml:xaerominimap:xaero_clientworldclass,pl:mixin:APP:architectury.mixins.json:MixinClientLevel,pl:mixin:APP:betterbiomeblend.mixins.json:MixinClientWorld,pl:mixin:APP:entityculling.mixins.json:ClientWorldMixin,pl:mixin:APP:terrablender.mixins.json:client.MixinClientLevel,pl:mixin:A}
	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2249) ~[client-1.18.1-20211210.034407-srg.jar%23161!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:betterthirdperson.mixins.json:MinecraftMixin,pl:mixin:APP:fallingleaves.mixins.json:MinecraftClientMixin,pl:mixin:APP:mixins.ipnext.json:MixinMinecraftClient,pl:mixin:APP:terrablender_forge.mixins.json:client.MixinMinecraft,pl:mixin:APP:securitycraft.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:678) ~[client-1.18.1-20211210.034407-srg.jar%23161!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:betterthirdperson.mixins.json:MinecraftMixin,pl:mixin:APP:fallingleaves.mixins.json:MinecraftClientMixin,pl:mixin:APP:mixins.ipnext.json:MixinMinecraftClient,pl:mixin:APP:terrablender_forge.mixins.json:client.MixinMinecraft,pl:mixin:APP:securitycraft.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.1-20211210.034407-srg.jar%23161!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.18.1-39.1.0.jar%2323!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Mod Resources, Default, Solar Flux Generated Resources

**Comment by SuperMartijn642** [comment]
OptiFine changes a whole lot of things, yet OptiFine does not say what it changes and it is closed source. It also changes a bunch of things from the way Forge normally handles them. For example, the crash you encountered is something that can never happen with just Forge.
This makes it pretty much impossible to know if something will break with OptiFine installed and I am not going to spend my time specifically testing random things with OptiFine installed.
For Moving Elevators, this means it may simply break when OptiFine is installed.

I fixed this particular crash now in Moving Elevators 1.3.6.
