### ISSUE TITLE
[Crash] Using Framed Blocks as a Cabin crashes client

### ISSUE THREAD

**Issue by arensagun2** [SuperMartijn642/MovingElevators#155]
**Version Info**

- Minecraft, 1.19.2
- Moving Elevators, 1.3.12

**Are you using OptiFine?**: 

No

**Steps to Reproduce**

Place a Elevator Controller, use a block from Framed Blocks Mod as the elevator base, configure elevator display by right clicking its side, then it crashes.

**Crash report (~/logs/latest.log)**

[07:44:04] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.ReportedException: Rendering screen
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:909) ~[client-1.19.2-20220805.130853-srg.jar%23529!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1115) ~[client-1.19.2-20220805.130853-srg.jar%23529!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23529!/:?]
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23529!/:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23529!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.2.8.jar%2395!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 5
	at xfacthd.framedblocks.api.util.client.QuadTable.getQuads(QuadTable.java:19) ~[FramedBlocks-6.8.2.jar%23417!/:6.8.2]
	at xfacthd.framedblocks.api.model.FramedBlockModel.getCamoQuads(FramedBlockModel.java:229) ~[FramedBlocks-6.8.2.jar%23417!/:6.8.2]
	at xfacthd.framedblocks.api.model.FramedBlockModel.getQuads(FramedBlockModel.java:97) ~[FramedBlocks-6.8.2.jar%23417!/:6.8.2]
	at com.supermartijn642.movingelevators.gui.preview.ElevatorPreviewRenderer.renderModel(ElevatorPreviewRenderer.java:100) ~[movingelevators-1.3.12-forge-mc1.19.jar%23459!/:?]
	at com.supermartijn642.movingelevators.gui.preview.ElevatorPreviewRenderer.renderBlock(ElevatorPreviewRenderer.java:85) ~[movingelevators-1.3.12-forge-mc1.19.jar%23459!/:?]
	at com.supermartijn642.movingelevators.gui.preview.ElevatorPreviewRenderer.renderPreview(ElevatorPreviewRenderer.java:54) ~[movingelevators-1.3.12-forge-mc1.19.jar%23459!/:?]
	at com.supermartijn642.movingelevators.gui.ElevatorPreviewWidget.render(ElevatorPreviewWidget.java:104) ~[movingelevators-1.3.12-forge-mc1.19.jar%23459!/:?]
	at com.supermartijn642.core.gui.widget.BaseWidget.render(BaseWidget.java:168) ~[supermartijn642corelib-1.1.6-forge-mc1.19.jar%23512!/:?]
	at com.supermartijn642.core.gui.widget.ObjectBaseWidget.render(ObjectBaseWidget.java:177) ~[supermartijn642corelib-1.1.6-forge-mc1.19.jar%23512!/:?]
	at com.supermartijn642.movingelevators.gui.ElevatorScreen.render(ElevatorScreen.java:111) ~[movingelevators-1.3.12-forge-mc1.19.jar%23459!/:?]
	at com.supermartijn642.movingelevators.gui.ElevatorScreen.render(ElevatorScreen.java:23) ~[movingelevators-1.3.12-forge-mc1.19.jar%23459!/:?]
	at com.supermartijn642.core.gui.widget.ObjectBaseWidget.render(ObjectBaseWidget.java:169) ~[supermartijn642corelib-1.1.6-forge-mc1.19.jar%23512!/:?]
	at com.supermartijn642.core.gui.WidgetScreen.m_6305_(WidgetScreen.java:76) ~[supermartijn642corelib-1.1.6-forge-mc1.19.jar%23512!/:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:441) ~[forge-1.19.2-43.2.8-universal.jar%23534!/:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:434) ~[forge-1.19.2-43.2.8-universal.jar%23534!/:?]
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:896) ~[client-1.19.2-20220805.130853-srg.jar%23529!/:?]
	... 17 more

**Comment by SuperMartijn642** [comment]
Thank you for reporting the issue 🙂

The part from the log you gave doesn't show the actual exception, could you provide the entire `logs/latest.log` file? (Preferably via something like [gist.github.com](gist.github.com), so it is a bit easier to read)

**Comment by SuperMartijn642** [comment]
> Caused by: java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 5

Ah nevermind, just overlooked it

**Comment by SuperMartijn642** [comment]
Should be fixed now in version 1.3.12a for Minecraft 1.19.2 and 1.19.3.

Thank you for reporting the issue!
