### ISSUE TITLE
[Crash]I used dirt on the elevator and then triggered a crash report from Fabric Season after it turned to grass

### ISSUE THREAD

**Issue by mss0517** [SuperMartijn642/MovingElevators#185]
It was normal when it was still dirt, so at first there was no way to determine what triggered the error.
I wasn't sure whether to reply to you or the author of Fabric Season.
Consider this a tip for those who have encountered the Tesselating block model.
(Translated from DeepL)

**Version Info**
- Minecraft, 1.20.1
- Moving Elevators, 1.4.3b

**Are you using OptiFine?**:No

**Steps to Reproduce**
I used grass block on the elevator.

**Crash report (~/logs/latest.log)**
Description: Tesselating block model

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_5321.method_29177()" because "dimension" is null
	at io.github.lucaargolo.seasons.utils.ModConfig.isValidInDimension(ModConfig.java:118)
	at io.github.lucaargolo.seasons.FabricSeasons.getCurrentSeason(FabricSeasons.java:219)
	at io.github.lucaargolo.seasons.FabricSeasons.injectBiomeTemperature(FabricSeasons.java:345)
	at net.minecraft.class_4538.method_23753(class_4538.java:1029)
	at net.minecraft.class_4538.method_23752(class_4538.java:63)
	at net.minecraft.class_1163.method_4965(class_1163.java:14)
	at net.minecraft.class_1163.method_4962(class_1163.java:18)
	at net.minecraft.class_324.method_1693(class_324.java:48)
	at net.minecraft.class_324.method_1697(class_324.java:123)
	at net.minecraft.class_778.method_23073(class_778.java:134)
	at net.minecraft.class_778.method_3363(class_778.java:120)
	at net.minecraft.class_778.method_3361(class_778.java:77)
	at net.minecraft.class_778.method_3374(class_778.java:48)
	at net.minecraft.class_776.method_3355(class_776.java:60)
	at com.supermartijn642.movingelevators.elevator.ElevatorGroupRenderer.renderGroupBlocks(ElevatorGroupRenderer.java:100)
	at com.supermartijn642.movingelevators.elevator.ElevatorGroupRenderer.renderBlocks(ElevatorGroupRenderer.java:56)
	at net.minecraft.class_761.handler$foh000$movingelevators$renderChunkLayer(class_761.java:26941)
	at net.minecraft.class_761.method_3251(class_761.java)
	at net.minecraft.class_761.method_22710(class_761.java:1254)
	at net.minecraft.class_757.method_3188(class_757.java:1110)
	at net.minecraft.class_757.method_3192(class_757.java:880)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at io.github.lucaargolo.seasons.utils.ModConfig.isValidInDimension(ModConfig.java:118)
	at io.github.lucaargolo.seasons.FabricSeasons.getCurrentSeason(FabricSeasons.java:219)
	at io.github.lucaargolo.seasons.FabricSeasons.injectBiomeTemperature(FabricSeasons.java:345)
	at net.minecraft.class_4538.method_23753(class_4538.java:1029)
	at net.minecraft.class_4538.method_23752(class_4538.java:63)
	at net.minecraft.class_1163.method_4965(class_1163.java:14)
	at net.minecraft.class_1163.method_4962(class_1163.java:18)
	at net.minecraft.class_324.method_1693(class_324.java:48)
	at net.minecraft.class_324.method_1697(class_324.java:123)
	at net.minecraft.class_778.method_23073(class_778.java:134)
	at net.minecraft.class_778.method_3363(class_778.java:120)
	at net.minecraft.class_778.method_3361(class_778.java:77)
	at net.minecraft.class_778.method_3374(class_778.java:48)
	at net.minecraft.class_776.method_3355(class_776.java:60)
	at com.supermartijn642.movingelevators.elevator.ElevatorGroupRenderer.renderGroupBlocks(ElevatorGroupRenderer.java:100)
	at com.supermartijn642.movingelevators.elevator.ElevatorGroupRenderer.renderBlocks(ElevatorGroupRenderer.java:56)
	at net.minecraft.class_761.handler$foh000$movingelevators$renderChunkLayer(class_761.java:26941)
	at net.minecraft.class_761.method_3251(class_761.java)
	at net.minecraft.class_761.method_22710(class_761.java:1254)
	at net.minecraft.class_757.method_3188(class_757.java:1110)

-- Block model being tesselated --
Details:
	Block: Block{minecraft:grass_block}[snowy=false]
	Block location: World: (-518,249,83), Section: (at 10,9,3 in -33,15,5; chunk contains blocks -528,-64,80 to -513,319,95), Region: (-2,0; contains chunks -64,0 to -33,31, blocks -1024,-64,0 to -513,319,511)
	Using AO: true
Stacktrace:
	at net.minecraft.class_778.method_3374(class_778.java:48)
	at net.minecraft.class_776.method_3355(class_776.java:60)
	at com.supermartijn642.movingelevators.elevator.ElevatorGroupRenderer.renderGroupBlocks(ElevatorGroupRenderer.java:100)
	at com.supermartijn642.movingelevators.elevator.ElevatorGroupRenderer.renderBlocks(ElevatorGroupRenderer.java:56)
	at net.minecraft.class_761.handler$foh000$movingelevators$renderChunkLayer(class_761.java:26941)
	at net.minecraft.class_761.method_3251(class_761.java)
	at net.minecraft.class_761.method_22710(class_761.java:1254)
	at net.minecraft.class_757.method_3188(class_757.java:1110)
	at net.minecraft.class_757.method_3192(class_757.java:880)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)

-- Block being tesselated --
Details:
	Block: Block{minecraft:grass_block}[snowy=false]
	Block location: World: (-518,249,83), Section: (at 10,9,3 in -33,15,5; chunk contains blocks -528,-64,80 to -513,319,95), Region: (-2,0; contains chunks -64,0 to -33,31, blocks -1024,-64,0 to -513,319,511)
Stacktrace:
	at net.minecraft.class_776.method_3355(class_776.java:60)
	at com.supermartijn642.movingelevators.elevator.ElevatorGroupRenderer.renderGroupBlocks(ElevatorGroupRenderer.java:100)
	at com.supermartijn642.movingelevators.elevator.ElevatorGroupRenderer.renderBlocks(ElevatorGroupRenderer.java:56)
	at net.minecraft.class_761.handler$foh000$movingelevators$renderChunkLayer(class_761.java:26941)
	at net.minecraft.class_761.method_3251(class_761.java)
	at net.minecraft.class_761.method_22710(class_761.java:1254)
	at net.minecraft.class_757.method_3188(class_757.java:1110)
	at net.minecraft.class_757.method_3192(class_757.java:880)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)

**Comment by SuperMartijn642** [comment]
Fixed now in Moving Elevators version 1.4.3c for Minecraft 1.20.
Thank you for reporting the issue!
