### ISSUE TITLE
[Crash] ...

### ISSUE THREAD

**Issue by Stiles52** [SuperMartijn642/MovingElevators#198]
**Version Info**
- Minecraft, Forge 1.16.5 36.2.39 and 41
- Moving Elevators, Testing with 1.4.5 and 1.4.4

**Are you using OptiFine?**: Yes

**Steps to Reproduce**
1 : I connected to the server with a shader: Complementary Unboun_r5.1.1. Without the shaders the mods are not present.

**Crash report (~/logs/latest.log)**

[20déc.2023 23:37:05.652] [main/INFO] [net.optifine.shaders.SMCLog/]: [Shaders] Shader info log: /shaders/final.fsh
1(10) : warning C7555: 'varying' is deprecated, use 'in/out' instead
1(104) : warning C7533: global function texture2DLod is deprecated after version 120
1(160) : warning C7533: global variable gl_FragColor is deprecated after version 120
[20déc.2023 23:37:05.653] [main/INFO] [net.optifine.shaders.SMCLog/]: [Shaders] Info log: final
Vertex info
-----------
1(10) : warning C7555: 'varying' is deprecated, use 'in/out' instead
1(170) : warning C7533: global variable gl_MultiTexCoord0 is deprecated after version 120
1(172) : warning C7533: global function ftransform is deprecated after version 120

Fragment info
-------------
1(10) : warning C7555: 'varying' is deprecated, use 'in/out' instead
1(104) : warning C7533: global function texture2DLod is deprecated after version 120
1(160) : warning C7533: global variable gl_FragColor is deprecated after version 120
[20déc.2023 23:37:05.653] [main/INFO] [net.optifine.shaders.SMCLog/]: [Shaders] Program loaded: final
[20déc.2023 23:37:05.654] [main/INFO] [net.optifine.shaders.SMCLog/]: [Shaders] usedColorBuffers: 10
[20déc.2023 23:37:05.654] [main/INFO] [net.optifine.shaders.SMCLog/]: [Shaders] usedDepthBuffers: 2
[20déc.2023 23:37:05.654] [main/INFO] [net.optifine.shaders.SMCLog/]: [Shaders] usedShadowColorBuffers: 0
[20déc.2023 23:37:05.654] [main/INFO] [net.optifine.shaders.SMCLog/]: [Shaders] usedShadowDepthBuffers: 1
[20déc.2023 23:37:05.654] [main/INFO] [net.optifine.shaders.SMCLog/]: [Shaders] usedColorAttachs: 10
[20déc.2023 23:37:05.654] [main/INFO] [net.optifine.shaders.SMCLog/]: [Shaders] usedDrawBuffers: 5
[20déc.2023 23:37:05.654] [main/INFO] [net.optifine.shaders.SMCLog/]: [Shaders] bindImageTextures: false
[20déc.2023 23:37:05.661] [main/INFO] [net.optifine.shaders.SMCLog/]: [Shaders] Framebuffer created: dfb
[20déc.2023 23:37:05.662] [main/INFO] [net.optifine.shaders.SMCLog/]: [Shaders] Framebuffer created: sfb
[20déc.2023 23:37:05.680] [main/INFO] [net.optifine.shaders.SMCLog/]: [Shaders] Reset model renderers
[20déc.2023 23:37:05.680] [main/INFO] [net.optifine.shaders.SMCLog/]: [Shaders] Reset world renderers
[20déc.2023 23:37:05.720] [main/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID ad13939b-7ab0-4c0d-8b78-9e9392cb80a7
[20déc.2023 23:37:05.724] [main/FATAL] [net.minecraft.client.Minecraft/]: Unreported exception thrown!
java.lang.NullPointerException: null
	at com.supermartijn642.core.render.RenderUtils.getCameraPosition(RenderUtils.java:90) ~[?:?]
	at com.supermartijn642.movingelevators.elevator.ElevatorGroupRenderer.renderBlocks(ElevatorGroupRenderer.java:59) ~[?:?]
	at net.minecraft.client.renderer.WorldRenderer.handler$zmk000$renderChunkLayer(WorldRenderer.java:8143) ~[?:?]
	at net.minecraft.client.renderer.WorldRenderer.func_228441_a_(WorldRenderer.java:2325) ~[?:?]
	at net.optifine.shaders.ShadersRender.renderShadowMap(ShadersRender.java:438) ~[?:?]
	at net.optifine.shaders.Shaders.beginRender(Shaders.java:4840) ~[?:?]
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:949) ~[?:?]
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:693) ~[?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:977) ~[?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?]
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:37) [forge-1.16.5-36.2.39.jar:36.2]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$506/217389263.call(Unknown Source) [forge-1.16.5-36.2.39.jar:36.2]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?]
[20déc.2023 23:37:08.846] [main/INFO] [DynamicSurroundings/ModuleServiceManager]: Starting action 'stop'
[20déc.2023 23:37:08.886] [main/INFO] [DynamicSurroundings/ModuleServiceManager]: Overall Action 'stop' took 39msecs
[20déc.2023 23:37:08.887] [main/INFO] [DynamicSurroundings/ModuleServiceManager]: Clearing reload state (playerJoined: true, reloadFired: true, customTagsEventFired: true, vanillaTagsEventFired: true)

**Comment by SuperMartijn642** [comment]
This is caused by OptiFine. OptiFine is closed source, so there's nothing I can do about it as I can't know what OptiFine does.

Consider using a better alternative like Oculus.
