### ISSUE TITLE
[Bug] World loading crash when entering a world with MovingElevators and shaders enabled

### ISSUE THREAD

**Issue by Sandoiitchisan** [SuperMartijn642/MovingElevators#212]
**Version Info**
- Minecraft, 1.20.1
- Moving Elevators, 1.4.6

**Are you using OptiFine?**: Yes

**Description of the Bug**
Loading a world with shaders enabled makes the game crash. Disabling shaders, entering the world and then enable them seems to work.

**Steps to Reproduce**
Use Optifine, any shaders and MovingElevators

---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 2024-02-27 18:20:59
Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "net.minecraft.client.Camera.m_90583_()" because "net.minecraft.client.Minecraft.m_91290_().f_114358_" is null
	at com.supermartijn642.core.render.RenderUtils.getCameraPosition(RenderUtils.java:94) ~[supermartijn642corelib-1.1.17-forge-mc1.20.1.jar%23213!/:?] {re:classloading}
	at com.supermartijn642.movingelevators.elevator.ElevatorGroupRenderer.renderBlocks(ElevatorGroupRenderer.java:56) ~[movingelevators-1.4.6-forge-mc1.20.1.jar%23209!/:?] {re:mixin,re:classloading}
	at net.minecraft.client.renderer.LevelRenderer.handler$zga000$renderChunkLayer(LevelRenderer.java:6322) ~[client-1.20.1-20230612.114412-srg.jar%23228!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:alexscaves.mixins.json:client.LevelRendererMixin,pl:mixin:APP:citadel.mixins.json:client.LevelRendererMixin,pl:mixin:APP:movingelevators.mixins.json:LevelRendererMixin,pl:mixin:APP:supermartijn642corelib.mixins.json:LevelRendererMixin,pl:mixin:APP:sereneseasons.mixins.json:client.MixinLevelRenderer,pl:mixin:A}
	at net.minecraft.client.renderer.LevelRenderer.m_172993_(LevelRenderer.java:2603) ~[client-1.20.1-20230612.114412-srg.jar%23228!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:alexscaves.mixins.json:client.LevelRendererMixin,pl:mixin:APP:citadel.mixins.json:client.LevelRendererMixin,pl:mixin:APP:movingelevators.mixins.json:LevelRendererMixin,pl:mixin:APP:supermartijn642corelib.mixins.json:LevelRendererMixin,pl:mixin:APP:sereneseasons.mixins.json:client.MixinLevelRenderer,pl:mixin:A}
	at net.optifine.shaders.ShadersRender.renderShadowMap(ShadersRender.java:464) ~[OptiFine_1.20.1_HD_U_I6.jar%23242!/:?] {re:classloading}
	at net.optifine.shaders.Shaders.beginRender(Shaders.java:4998) ~[OptiFine_1.20.1_HD_U_I6.jar%23242!/:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1584) ~[client-1.20.1-20230612.114412-srg.jar%23228!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:alexscaves.mixins.json:client.GameRendererMixin,pl:mixin:APP:forge-mca.mixin.json:client.MixinGameRenderer,pl:mixin:APP:immersive_aircraft.mixins.json:client.GameRendererMixin,pl:mixin:A}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:1279) ~[client-1.20.1-20230612.114412-srg.jar%23228!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:alexscaves.mixins.json:client.GameRendererMixin,pl:mixin:APP:forge-mca.mixin.json:client.MixinGameRenderer,pl:mixin:APP:immersive_aircraft.mixins.json:client.GameRendererMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%23228!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:alexscaves.mixins.json:client.MinecraftMixin,pl:mixin:APP:mixins.ipnext.json:MixinMinecraftClient,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23228!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:alexscaves.mixins.json:client.MinecraftMixin,pl:mixin:APP:mixins.ipnext.json:MixinMinecraftClient,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[La%20Sandwicherie.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.0.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.2.0.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.2.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
nullStacktrace:
	at com.supermartijn642.core.render.RenderUtils.getCameraPosition(RenderUtils.java:94) ~[supermartijn642corelib-1.1.17-forge-mc1.20.1.jar%23213!/:?] {re:classloading}
	at com.supermartijn642.movingelevators.elevator.ElevatorGroupRenderer.renderBlocks(ElevatorGroupRenderer.java:56) ~[movingelevators-1.4.6-forge-mc1.20.1.jar%23209!/:?] {re:mixin,re:classloading}
	at net.minecraft.client.renderer.LevelRenderer.handler$zga000$renderChunkLayer(LevelRenderer.java:6322) ~[client-1.20.1-20230612.114412-srg.jar%23228!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:alexscaves.mixins.json:client.LevelRendererMixin,pl:mixin:APP:citadel.mixins.json:client.LevelRendererMixin,pl:mixin:APP:movingelevators.mixins.json:LevelRendererMixin,pl:mixin:APP:supermartijn642corelib.mixins.json:LevelRendererMixin,pl:mixin:APP:sereneseasons.mixins.json:client.MixinLevelRenderer,pl:mixin:A}
	at net.minecraft.client.renderer.LevelRenderer.m_172993_(LevelRenderer.java:2603) ~[client-1.20.1-20230612.114412-srg.jar%23228!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:alexscaves.mixins.json:client.LevelRendererMixin,pl:mixin:APP:citadel.mixins.json:client.LevelRendererMixin,pl:mixin:APP:movingelevators.mixins.json:LevelRendererMixin,pl:mixin:APP:supermartijn642corelib.mixins.json:LevelRendererMixin,pl:mixin:APP:sereneseasons.mixins.json:client.MixinLevelRenderer,pl:mixin:A}
	at net.optifine.shaders.ShadersRender.renderShadowMap(ShadersRender.java:464) ~[OptiFine_1.20.1_HD_U_I6.jar%23242!/:?] {re:classloading}
	at net.optifine.shaders.Shaders.beginRender(Shaders.java:4998) ~[OptiFine_1.20.1_HD_U_I6.jar%23242!/:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1584) ~[client-1.20.1-20230612.114412-srg.jar%23228!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:alexscaves.mixins.json:client.GameRendererMixin,pl:mixin:APP:forge-mca.mixin.json:client.MixinGameRenderer,pl:mixin:APP:immersive_aircraft.mixins.json:client.GameRendererMixin,pl:mixin:A}
-- Affected level --
Details:
	All players: 1 total; [LocalPlayer['MrSandwich34'/63, l='ClientLevel', x=809.75, y=75.00, z=-5566.07]]
	Chunk stats: 729, 453
	Level dimension: minecraft:overworld
	Level spawn location: World: (96,75,16), Section: (at 0,11,0 in 6,4,1; chunk contains blocks 96,-64,16 to 111,319,31), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 691295 game time, 923104 day time
	Server brand: forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.ClientLevel.m_6026_(ClientLevel.java:590) ~[client-1.20.1-20230612.114412-srg.jar%23228!/:?] {re:mixin,xf:OptiFine:default,re:computing_frames,xf:OptiFine:default,re:classloading,xf:OptiFine:default,pl:mixin:APP:citadel.mixins.json:client.ClientLevelMixin,pl:mixin:APP:alexscaves.mixins.json:client.ClientLevelMixin,pl:mixin:APP:architectury.mixins.json:MixinClientLevel,pl:mixin:A}
	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2319) ~[client-1.20.1-20230612.114412-srg.jar%23228!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:alexscaves.mixins.json:client.MinecraftMixin,pl:mixin:APP:mixins.ipnext.json:MixinMinecraftClient,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:740) ~[client-1.20.1-20230612.114412-srg.jar%23228!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:alexscaves.mixins.json:client.MinecraftMixin,pl:mixin:APP:mixins.ipnext.json:MixinMinecraftClient,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[La%20Sandwicherie.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.0.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.2.0.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.2.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, mod_resources

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 665462696 bytes (634 MiB) / 1811939328 bytes (1728 MiB) up to 7314866176 bytes (6976 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 5600 6-Core Processor              
	Identifier: AuthenticAMD Family 25 Model 33 Stepping 0
	Microarchitecture: Zen 3
	Frequency (GHz): 4.08
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: AMD Radeon RX 6750 XT
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x73df
	Graphics card #0 versionInfo: DriverVersion=31.0.23013.1023
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 3.60
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 3.60
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 48655.45
	Virtual memory used (MB): 42963.94
	Swap memory total (MB): 15964.64
	Swap memory used (MB): 58.10
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6947M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: La Sandwicherie
	Backend library: LWJGL version 3.3.1 build 7
	Backend API: AMD Radeon RX 6750 XT GL version 4.6.0 Core Profile Context 23.12.1.231124, ATI Technologies Inc.
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: id=1000, source=API, type=ERROR, severity=HIGH, message='glBindTexture has generated an error (GL_INVALID_OPERATION)' x 1
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, mod_resources
	Current Language: fr_fr
	CPU: 12x AMD Ryzen 5 5600 6-Core Processor 
	OptiFine Version: OptiFine_1.20.1_HD_U_I6
	OptiFine Build: 20231221-120401
	Render Distance Chunks: 32
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: Sildur's+Vibrant+Shaders+v1.51+Extreme-VL.zip
	OpenGlVersion: 4.6.0 Core Profile Context 23.12.1.231124
	OpenGlRenderer: AMD Radeon RX 6750 XT
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 12
	ModLauncher: 10.0.9+10.0.9+main.dcd20f30
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.5.jar eventbus PLUGINSERVICE 
		fmlloader-1.20.1-47.2.0.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.20.1-47.2.0.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.20.1-47.2.0.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.20.1-47.2.0.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.20.1-47.2.0.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.9.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar OptiFine TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
		kotlinforforge@4.10.0
		lowcodefml@null
	Mod List: 
		client-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		mcw-bridges-2.1.1-mc1.20.1forge.jar               |Macaw's Bridges               |mcwbridges                    |2.1.1               |DONE      |Manifest: NOSIGNATURE
		YungsBetterDungeons-1.20-Forge-4.0.3.jar          |YUNG's Better Dungeons        |betterdungeons                |1.20-Forge-4.0.3    |DONE      |Manifest: NOSIGNATURE
		libIPN-forge-1.20-4.0.1.jar                       |libIPN                        |libipn                        |4.0.1               |DONE      |Manifest: NOSIGNATURE
		TerraBlender-forge-1.20.1-3.0.1.4.jar             |TerraBlender                  |terrablender                  |3.0.1.4             |DONE      |Manifest: NOSIGNATURE
		supermartijn642configlib-1.1.8-forge-mc1.20.jar   |SuperMartijn642's Config Libra|supermartijn642configlib      |1.1.8               |DONE      |Manifest: NOSIGNATURE
		YungsBetterWitchHuts-1.20-Forge-3.0.3.jar         |YUNG's Better Witch Huts      |betterwitchhuts               |1.20-Forge-3.0.3    |DONE      |Manifest: NOSIGNATURE
		BiomesOPlenty-1.20.1-18.0.0.592.jar               |Biomes O' Plenty              |biomesoplenty                 |18.0.0.592          |DONE      |Manifest: NOSIGNATURE
		Jade-1.20.1-forge-11.7.1.jar                      |Jade                          |jade                          |11.7.1              |DONE      |Manifest: NOSIGNATURE
		supermartijn642corelib-1.1.17-forge-mc1.20.1.jar  |SuperMartijn642's Core Lib    |supermartijn642corelib        |1.1.17              |DONE      |Manifest: NOSIGNATURE
		movingelevators-1.4.6-forge-mc1.20.1.jar          |Moving Elevators              |movingelevators               |1.4.6               |DONE      |Manifest: NOSIGNATURE
		YungsBridges-1.20-Forge-4.0.3.jar                 |YUNG's Bridges                |yungsbridges                  |1.20-Forge-4.0.3    |DONE      |Manifest: NOSIGNATURE
		YungsBetterOceanMonuments-1.20-Forge-3.0.4.jar    |YUNG's Better Ocean Monuments |betteroceanmonuments          |1.20-Forge-3.0.4    |DONE      |Manifest: NOSIGNATURE
		kffmod-4.10.0.jar                                 |Kotlin For Forge              |kotlinforforge                |4.10.0              |DONE      |Manifest: NOSIGNATURE
		immersive_aircraft-0.7.1+1.20.1-forge.jar         |Immersive Aircraft            |immersive_aircraft            |0.7.1+1.20.1        |DONE      |Manifest: NOSIGNATURE
		soundphysics-forge-1.20.1-1.1.2.jar               |Sound Physics Remastered      |sound_physics_remastered      |1.20.1-1.1.2        |DONE      |Manifest: NOSIGNATURE
		waystones-forge-1.20-14.1.3.jar                   |Waystones                     |waystones                     |14.1.3              |DONE      |Manifest: NOSIGNATURE
		gravestone-1.20.1-1.0.10.jar                      |Gravestone Mod                |gravestone                    |1.20.1-1.0.10       |DONE      |Manifest: NOSIGNATURE
		journeymap-1.20.1-5.9.18-forge.jar                |Journeymap                    |journeymap                    |5.9.18              |DONE      |Manifest: NOSIGNATURE
		citadel-2.5.3-1.20.1.jar                          |Citadel                       |citadel                       |2.5.3               |DONE      |Manifest: NOSIGNATURE
		alexscaves-1.1.1.jar                              |Alex's Caves                  |alexscaves                    |1.1.1               |DONE      |Manifest: NOSIGNATURE
		alexsmobs-1.22.7.jar                              |Alex's Mobs                   |alexsmobs                     |1.22.7              |DONE      |Manifest: NOSIGNATURE
		YungsExtras-1.20-Forge-4.0.3.jar                  |YUNG's Extras                 |yungsextras                   |1.20-Forge-4.0.3    |DONE      |Manifest: NOSIGNATURE
		SereneSeasons-1.20.1-9.0.0.46.jar                 |Serene Seasons                |sereneseasons                 |9.0.0.46            |DONE      |Manifest: NOSIGNATURE
		YungsApi-1.20-Forge-4.0.3.jar                     |YUNG's API                    |yungsapi                      |1.20-Forge-4.0.3    |DONE      |Manifest: NOSIGNATURE
		YungsBetterStrongholds-1.20-Forge-4.0.3.jar       |YUNG's Better Strongholds     |betterstrongholds             |1.20-Forge-4.0.3    |DONE      |Manifest: NOSIGNATURE
		InventoryProfilesNext-forge-1.20-1.10.9.jar       |Inventory Profiles Next       |inventoryprofilesnext         |1.10.9              |DONE      |Manifest: NOSIGNATURE
		YungsBetterDesertTemples-1.20-Forge-3.0.3.jar     |YUNG's Better Desert Temples  |betterdeserttemples           |1.20-Forge-3.0.3    |DONE      |Manifest: NOSIGNATURE
		architectury-9.1.13-forge.jar                     |Architectury                  |architectury                  |9.1.13              |DONE      |Manifest: NOSIGNATURE
		minecraft-comes-alive-7.5.14+1.20.1-universal.jar |Minecraft Comes Alive         |mca                           |7.5.14+1.20.1       |DONE      |Manifest: NOSIGNATURE
		balm-forge-1.20.1-7.2.1.jar                       |Balm                          |balm                          |7.2.1               |DONE      |Manifest: NOSIGNATURE
		YungsBetterNetherFortresses-1.20-Forge-2.0.5.jar  |YUNG's Better Nether Fortresse|betterfortresses              |1.20-Forge-2.0.5    |DONE      |Manifest: NOSIGNATURE
		forge-1.20.1-47.2.0-universal.jar                 |Forge                         |forge                         |47.2.0              |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		Towns-and-Towers-1.12-Fabric+Forge.jar            |Towns and Towers              |t_and_t                       |0.0NONE             |DONE      |Manifest: NOSIGNATURE
		YungsBetterMineshafts-1.20-Forge-4.0.4.jar        |YUNG's Better Mineshafts      |bettermineshafts              |1.20-Forge-4.0.4    |DONE      |Manifest: NOSIGNATURE
		YungsBetterJungleTemples-1.20-Forge-2.0.4.jar     |YUNG's Better Jungle Temples  |betterjungletemples           |1.20-Forge-2.0.4    |DONE      |Manifest: NOSIGNATURE
		cristellib-1.1.5-forge.jar                        |Cristel Lib                   |cristellib                    |1.1.5               |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 0a20bf57-caba-42b2-9320-26124c19f140
	FML: 47.2
	Forge: net.minecraftforge:47.2.0

**Comment by SuperMartijn642** [comment]
This is caused by OptiFine. OptiFine is closed source, so I can't know what they're changing. Thus not much I can do about it.
You can use Iris or Oculus instead of OptiFine.

#198, #200 for reference.

**Comment by Sandoiitchisan** [comment]
Ok, I'm gonna try that then ;)
Thanks for the replying, I've been searching for a while without finding
anything
