### ISSUE TITLE
Crashing on Neoforge Server

### ISSUE THREAD

**Issue by TiefSeeTaucher69** [SuperMartijn642/MovingElevators#244]
Version 1.4.9 for Neoforge 1.21.2

Hey, i just tried to run ur mod on my server and it always crashes and i dont know why.
On the Client however it works, on the same neoforge version(21.2.1-beta)

Error-Message:

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: main
Stacktrace:
        at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:220) ~[securejarhandler-3.0.8.jar:?] {}
-- Mod loading issue for: movingelevators --
Details:
        Caused by 0: java.lang.NoClassDefFoundError: net/minecraft/client/resources/model/MissingBlockModel
                at TRANSFORMER/supermartijn642corelib@1.1.17/com.supermartijn642.core.item.BaseBlockItem.removeDescriptionAndModelFromProperties(BaseBlockItem.java:50) ~[supermartijn642corelib-1.1.17-neoforge-mc1.21.3.jar%23160!/:?] {re:classloading}
                at TRANSFORMER/supermartijn642corelib@1.1.17/com.supermartijn642.core.item.BaseBlockItem.<init>(BaseBlockItem.java:45) ~[supermartijn642corelib-1.1.17-neoforge-mc1.21.3.jar%23160!/:?] {re:classloading}
                at TRANSFORMER/movingelevators@1.4.9/com.supermartijn642.movingelevators.MovingElevators.lambda$register$8(MovingElevators.java:101) ~[movingelevators-1.4.9-neoforge-mc1.21.3%20(1).jar%23158!/:?] {re:classloading}
                at TRANSFORMER/supermartijn642corelib@1.1.17/com.supermartijn642.core.registry.RegistrationHandler.registerEntries(RegistrationHandler.java:520) ~[supermartijn642corelib-1.1.17-neoforge-mc1.21.3.jar%23160!/:?] {re:classloading}
                at TRANSFORMER/supermartijn642corelib@1.1.17/com.supermartijn642.core.registry.RegistrationHandler.handleRegistry(RegistrationHandler.java:509) ~[supermartijn642corelib-1.1.17-neoforge-mc1.21.3.jar%23160!/:?] {re:classloading}
                at TRANSFORMER/supermartijn642corelib@1.1.17/com.supermartijn642.core.registry.RegistrationHandler.handleRegisterEvent(RegistrationHandler.java:499) ~[supermartijn642corelib-1.1.17-neoforge-mc1.21.3.jar%23160!/:?] {re:classloading}
                at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.ConsumerEventHandler.invoke(ConsumerEventHandler.java:26) ~[bus-8.0.2.jar%2379!/:?] {}
                at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:350) ~[bus-8.0.2.jar%2379!/:?] {}
                at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:329) ~[bus-8.0.2.jar%2379!/:?] {}
                at MC-BOOTSTRAP/fml_loader@4.0.29/net.neoforged.fml.ModContainer.acceptEvent(ModContainer.java:177) ~[loader-4.0.29.jar%2372!/:4.0] {}
                at MC-BOOTSTRAP/fml_loader@4.0.29/net.neoforged.fml.ModLoader.lambda$postEventWithWrapInModOrder$16(ModLoader.java:379) ~[loader-4.0.29.jar%2372!/:4.0] {}
                at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {re:computing_frames,re:mixin}
                at MC-BOOTSTRAP/fml_loader@4.0.29/net.neoforged.fml.ModList.forEachModInOrder(ModList.java:174) ~[loader-4.0.29.jar%2372!/:4.0] {}
                at MC-BOOTSTRAP/fml_loader@4.0.29/net.neoforged.fml.ModLoader.postEventWithWrapInModOrder(ModLoader.java:377) ~[loader-4.0.29.jar%2372!/:4.0] {}
                at MC-BOOTSTRAP/fml_loader@4.0.29/net.neoforged.fml.ModLoader.postEventWrapContainerInModOrder(ModLoader.java:368) ~[loader-4.0.29.jar%2372!/:4.0] {}
                at TRANSFORMER/neoforge@21.2.1-beta/net.neoforged.neoforge.registries.GameData.postRegisterEvents(GameData.java:90) ~[neoforge-21.2.1-beta-universal.jar%23153!/:?] {re:mixin,re:classloading,pl:mixin:APP:supermartijn642corelib.mixins.json:GameDataMixin from mod supermartijn642corelib,pl:mixin:A}
                at TRANSFORMER/neoforge@21.2.1-beta/net.neoforged.neoforge.internal.CommonModLoader.lambda$begin$0(CommonModLoader.java:54) ~[neoforge-21.2.1-beta-universal.jar%23153!/:?] {re:classloading}
                at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
                at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?] {}
                at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?] {}
                at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?] {}

        Mod file: /C:/Users/benja/Desktop/mc-server-test/mods/movingelevators-1.4.9-neoforge-mc1.21.3 (1).jar
        Failure message: Moving Elevators (movingelevators) encountered an error while dispatching the net.neoforged.neoforge.registries.RegisterEvent event
                java.lang.NoClassDefFoundError: net/minecraft/client/resources/model/MissingBlockModel
        Mod version: 1.4.9
        Mod issues URL: https://github.com/SuperMartijn642/MovingElevators/issues
        Exception message: java.lang.ClassNotFoundException: net.minecraft.client.resources.model.MissingBlockModel
Stacktrace:
        at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:220) ~[securejarhandler-3.0.8.jar:?] {}
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?] {}
        at TRANSFORMER/supermartijn642corelib@1.1.17/com.supermartijn642.core.item.BaseBlockItem.removeDescriptionAndModelFromProperties(BaseBlockItem.java:50) ~[supermartijn642corelib-1.1.17-neoforge-mc1.21.3.jar%23160!/:?] {re:classloading}
        at TRANSFORMER/supermartijn642corelib@1.1.17/com.supermartijn642.core.item.BaseBlockItem.<init>(BaseBlockItem.java:45) ~[supermartijn642corelib-1.1.17-neoforge-mc1.21.3.jar%23160!/:?] {re:classloading}
        at TRANSFORMER/movingelevators@1.4.9/com.supermartijn642.movingelevators.MovingElevators.lambda$register$8(MovingElevators.java:101) ~[movingelevators-1.4.9-neoforge-mc1.21.3%20(1).jar%23158!/:?] {re:classloading}
        at TRANSFORMER/supermartijn642corelib@1.1.17/com.supermartijn642.core.registry.RegistrationHandler.registerEntries(RegistrationHandler.java:520) ~[supermartijn642corelib-1.1.17-neoforge-mc1.21.3.jar%23160!/:?] {re:classloading}
        at TRANSFORMER/supermartijn642corelib@1.1.17/com.supermartijn642.core.registry.RegistrationHandler.handleRegistry(RegistrationHandler.java:509) ~[supermartijn642corelib-1.1.17-neoforge-mc1.21.3.jar%23160!/:?] {re:classloading}
        at TRANSFORMER/supermartijn642corelib@1.1.17/com.supermartijn642.core.registry.RegistrationHandler.handleRegisterEvent(RegistrationHandler.java:499) ~[supermartijn642corelib-1.1.17-neoforge-mc1.21.3.jar%23160!/:?] {re:classloading}
        at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.ConsumerEventHandler.invoke(ConsumerEventHandler.java:26) ~[bus-8.0.2.jar%2379!/:?] {}
        at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:350) ~[bus-8.0.2.jar%2379!/:?] {}
        at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:329) ~[bus-8.0.2.jar%2379!/:?] {}
        at MC-BOOTSTRAP/fml_loader@4.0.29/net.neoforged.fml.ModContainer.acceptEvent(ModContainer.java:177) ~[loader-4.0.29.jar%2372!/:4.0] {}
        at MC-BOOTSTRAP/fml_loader@4.0.29/net.neoforged.fml.ModLoader.lambda$postEventWithWrapInModOrder$16(ModLoader.java:379) ~[loader-4.0.29.jar%2372!/:4.0] {}
        at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {re:computing_frames,re:mixin}
        at MC-BOOTSTRAP/fml_loader@4.0.29/net.neoforged.fml.ModList.forEachModInOrder(ModList.java:174) ~[loader-4.0.29.jar%2372!/:4.0] {}
        at MC-BOOTSTRAP/fml_loader@4.0.29/net.neoforged.fml.ModLoader.postEventWithWrapInModOrder(ModLoader.java:377) ~[loader-4.0.29.jar%2372!/:4.0] {}
        at MC-BOOTSTRAP/fml_loader@4.0.29/net.neoforged.fml.ModLoader.postEventWrapContainerInModOrder(ModLoader.java:368) ~[loader-4.0.29.jar%2372!/:4.0] {}
        at TRANSFORMER/neoforge@21.2.1-beta/net.neoforged.neoforge.registries.GameData.postRegisterEvents(GameData.java:90) ~[neoforge-21.2.1-beta-universal.jar%23153!/:?] {re:mixin,re:classloading,pl:mixin:APP:supermartijn642corelib.mixins.json:GameDataMixin from mod supermartijn642corelib,pl:mixin:A}
        at TRANSFORMER/neoforge@21.2.1-beta/net.neoforged.neoforge.internal.CommonModLoader.lambda$begin$0(CommonModLoader.java:54) ~[neoforge-21.2.1-beta-universal.jar%23153!/:?] {re:classloading}
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?] {}
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?] {}
        at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?] {}

-- System Details --
Details:
        Minecraft Version: 1.21.2
        Minecraft Version ID: 1.21.2
        Operating System: Windows 11 (amd64) version 10.0
        Java Version: 22.0.1, Oracle Corporation
        Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
        Memory: 208943920 bytes (199 MiB) / 364904448 bytes (348 MiB) up to 8371830784 bytes (7984 MiB)
        CPUs: 16
        Processor Vendor: AuthenticAMD
        Processor Name: AMD Ryzen 7 7800X3D 8-Core Processor
        Identifier: AuthenticAMD Family 25 Model 97 Stepping 2
        Microarchitecture: Zen 3
        Frequency (GHz): 4.20
        Number of physical packages: 1
        Number of physical CPUs: 8
        Number of logical CPUs: 16
        Graphics card #0 name: NVIDIA GeForce RTX 4060
        Graphics card #0 vendor: NVIDIA
        Graphics card #0 VRAM (MiB): 8188.00
        Graphics card #0 deviceId: VideoController1
        Graphics card #0 versionInfo: 32.0.15.6590
        Graphics card #1 name: AMD Radeon(TM) Graphics
        Graphics card #1 vendor: Advanced Micro Devices, Inc.
        Graphics card #1 VRAM (MiB): 512.00
        Graphics card #1 deviceId: VideoController2
        Graphics card #1 versionInfo: 32.0.11037.4004
        Memory slot #0 capacity (MiB): 16384.00
        Memory slot #0 clockSpeed (GHz): 4.80
        Memory slot #0 type: Unknown
        Memory slot #1 capacity (MiB): 16384.00
        Memory slot #1 clockSpeed (GHz): 4.80
        Memory slot #1 type: Unknown
        Virtual memory max (MiB): 61630.52
        Virtual memory used (MiB): 24402.47
        Swap memory total (MiB): 29696.00
        Swap memory used (MiB): 162.75
        Space in storage for jna.tmpdir (MiB): <path not set>
        Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): <path not set>
        Space in storage for io.netty.native.workdir (MiB): <path not set>
        Space in storage for java.io.tmpdir (MiB): available: 492830.84, total: 953451.00
        Space in storage for workdir (MiB): available: 492830.84, total: 953451.00
        JVM Flags: 0 total;
        ModLauncher: 11.0.4+main.d2e20e43
        ModLauncher launch target: forgeserver
        ModLauncher services:
                sponge-mixin-0.15.2+mixin.0.8.7.jar mixin PLUGINSERVICE
                loader-4.0.29.jar slf4jfixer PLUGINSERVICE
                loader-4.0.29.jar runtime_enum_extender PLUGINSERVICE
                at-modlauncher-10.0.1.jar accesstransformer PLUGINSERVICE
                loader-4.0.29.jar runtimedistcleaner PLUGINSERVICE
                modlauncher-11.0.4.jar mixin TRANSFORMATIONSERVICE
                modlauncher-11.0.4.jar fml TRANSFORMATIONSERVICE
        FML Language Providers:
                javafml@4.0
                lowcodefml@4.0
                minecraft@4.0
        Mod List:
                balm-neoforge-1.21.3-21.3.1.jar                   |Balm                          |balm                          |21.3.1              |Manifest: NOSIGNATURE
                clientsort-neoforge-1.21.2-21.2.0-beta.02.jar     |ClientSort                    |clientsort                    |21.2.0-beta.02      |Manifest: NOSIGNATURE
                FallingTree-1.21.2-1.21.2.1.jar                   |FallingTree                   |fallingtree                   |1.21.2.1            |Manifest: NOSIGNATURE
                gravestone-neoforge-1.21.2-1.0.24.jar             |Gravestone Mod                |gravestone                    |1.21.2-1.0.24       |Manifest: NOSIGNATURE
                kuma-api-neoforge-21.3.1-SNAPSHOT.jar             |KumaAPI                       |kuma_api                      |21.3.1-SNAPSHOT     |Manifest: NOSIGNATURE
                server-1.21.2-20241022.151510-srg.jar             |Minecraft                     |minecraft                     |1.21.2              |Manifest: NOSIGNATURE
                movingelevators-1.4.9-neoforge-mc1.21.3 (1).jar   |Moving Elevators              |movingelevators               |1.4.9               |Manifest: NOSIGNATURE
                neoforge-21.2.1-beta-universal.jar                |NeoForge                      |neoforge                      |21.2.1-beta         |Manifest: NOSIGNATURE
                supermartijn642configlib-1.1.8-neoforge-mc1.21.jar|SuperMartijn642's Config Libra|supermartijn642configlib      |1.1.8               |Manifest: NOSIGNATURE
                supermartijn642corelib-1.1.17-neoforge-mc1.21.3.ja|SuperMartijn642's Core Lib    |supermartijn642corelib        |1.1.17              |Manifest: NOSIGNATURE
                trashslot-neoforge-1.21.3-21.3.1.jar              |TrashSlot                     |trashslot                     |21.3.1              |Manifest: NOSIGNATURE
                zume-1.1.2.jar                                    |Zume                          |zume                          |1.1.2               |Manifest: NOSIGNATURE
        Crash Report UUID: 22dec2ce-8abc-4ebb-9396-678b71841910
        FML: 4.0.29
        NeoForge: 21.2.1-beta
[14:00:20] [main/ERROR] [minecraft/Main]: Failed to start the minecraft server
net.neoforged.fml.ModLoadingException: Loading errors encountered:
        - Moving Elevators (movingelevators) encountered an error while dispatching the net.neoforged.neoforge.registries.RegisterEvent event
          java.lang.NoClassDefFoundError: net/minecraft/client/resources/model/MissingBlockModel

        at MC-BOOTSTRAP/fml_loader@4.0.29/net.neoforged.fml.ModLoader.waitForFuture(ModLoader.java:281) ~[loader-4.0.29.jar%2372!/:4.0] {}
        at MC-BOOTSTRAP/fml_loader@4.0.29/net.neoforged.fml.ModLoader.waitForTask(ModLoader.java:183) ~[loader-4.0.29.jar%2372!/:4.0] {}
        at MC-BOOTSTRAP/fml_loader@4.0.29/net.neoforged.fml.ModLoader.runInitTask(ModLoader.java:163) ~[loader-4.0.29.jar%2372!/:4.0] {}
        at TRANSFORMER/neoforge@21.2.1-beta/net.neoforged.neoforge.internal.CommonModLoader.begin(CommonModLoader.java:51) ~[neoforge-21.2.1-beta-universal.jar%23153!/:?] {re:classloading}
        at TRANSFORMER/neoforge@21.2.1-beta/net.neoforged.neoforge.server.loading.ServerModLoader.load(ServerModLoader.java:34) ~[neoforge-21.2.1-beta-universal.jar%23153!/:?] {re:classloading}
        at TRANSFORMER/minecraft@1.21.2/net.minecraft.server.Main.main(Main.java:124) ~[server-1.21.2-20241022.151510-srg.jar%23152!/:?] {re:classloading}
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?] {}
        at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?] {}
        at MC-BOOTSTRAP/fml_loader@4.0.29/net.neoforged.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:136) ~[loader-4.0.29.jar%2372!/:4.0] {}
        at MC-BOOTSTRAP/fml_loader@4.0.29/net.neoforged.fml.loading.targets.CommonLaunchHandler.serverService(CommonLaunchHandler.java:128) ~[loader-4.0.29.jar%2372!/:4.0] {}
        at MC-BOOTSTRAP/fml_loader@4.0.29/net.neoforged.fml.loading.targets.CommonServerLaunchHandler.runService(CommonServerLaunchHandler.java:32) ~[loader-4.0.29.jar%2372!/:4.0] {}
        at MC-BOOTSTRAP/fml_loader@4.0.29/net.neoforged.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:118) ~[loader-4.0.29.jar%2372!/:4.0] {}
        at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-11.0.4.jar%2374!/:?] {}
        at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-11.0.4.jar%2374!/:?] {}
        at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-11.0.4.jar%2374!/:?] {}
        at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.run(Launcher.java:103) [modlauncher-11.0.4.jar%2374!/:?] {}
        at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.main(Launcher.java:74) [modlauncher-11.0.4.jar%2374!/:?] {}
        at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-11.0.4.jar%2374!/:?] {}
        at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-11.0.4.jar%2374!/:?] {}
        at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.run(BootstrapLauncher.java:210) [bootstraplauncher-2.0.2.jar:?] {}
        at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:69) [bootstraplauncher-2.0.2.jar:?] {}

**Comment by TiefSeeTaucher69** [comment]
Crash Report File:
[crash-2024-10-25_14.00.20-fml.txt](https://github.com/user-attachments/files/17521764/crash-2024-10-25_14.00.20-fml.txt)
Debug Log File:
[debug.log](https://github.com/user-attachments/files/17521788/debug.log)

**Comment by SuperMartijn642** [comment]
Should be fixed now in version 1.1.17a for Minecraft 1.21.2 & 1.21.3.
Thank you for reporting the issue!
