### ISSUE TITLE
[Crash] ...

### ISSUE THREAD

**Issue by MichaelLazarevic** [SuperMartijn642/MovingElevators#61]
**Version Info**
- Minecraft, ... 1.12.2
- Moving Elevators, ...movingelevators-1.2.4b

**Steps to Reproduce**
...
Clicked on side of Controller with Dark Oak Log
**Crash report (~/logs/latest.log)**
...
---- Minecraft Crash Report ----
 
WARNING: coremods are present:
  AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-1.7.0-232-universal.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
  EngineersDoorsLoadingPlugin (engineers_doors-1.12.2-0.9.1.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  AstralCore (astralsorcery-1.12.2-1.10.19.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  FutureMC (future-mc-1.12.2-0.2.6.1.jar)
Contact their authors BEFORE contacting forge
 
// I bet Cylons wouldn't have this problem.
 
Time: 6/5/21 8:35 PM
Description: Rendering Block Entity
 
java.lang.NullPointerException: Rendering Block Entity
	at net.minecraft.block.BlockLog.func_180642_a(BlockLog.java:47)
	at com.supermartijn642.movingelevators.METile.getCamoBlock(METile.java:93)
	at com.supermartijn642.movingelevators.METileRenderer.renderCamouflage(METileRenderer.java:53)
	at com.supermartijn642.movingelevators.METileRenderer.render(METileRenderer.java:44)
	at com.supermartijn642.movingelevators.METileRenderer.func_192841_a(METileRenderer.java:18)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_192854_a(TileEntityRendererDispatcher.java:156)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:131)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:715)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1347)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1062)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
 
 
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
 
-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.block.BlockLog.func_180642_a(BlockLog.java:47)
	at com.supermartijn642.movingelevators.METile.getCamoBlock(METile.java:93)
	at com.supermartijn642.movingelevators.METileRenderer.renderCamouflage(METileRenderer.java:53)
	at com.supermartijn642.movingelevators.METileRenderer.render(METileRenderer.java:44)
	at com.supermartijn642.movingelevators.METileRenderer.func_192841_a(METileRenderer.java:18)
 
-- Block Entity Details --
Details:
	Name: movingelevators:elevatorblocktile // com.supermartijn642.movingelevators.ElevatorBlockTile
	Block type: ID #2064 (tile.movingelevators:elevator_block // com.supermartijn642.movingelevators.ElevatorBlock // movingelevators:elevator_block)
	Block data value: 2 / 0x2 / 0b0010
	Block location: World: (236,75,504), Chunk: (at 12,4,8 in 14,31; contains blocks 224,0,496 to 239,255,511), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Actual block type: ID #2064 (tile.movingelevators:elevator_block // com.supermartijn642.movingelevators.ElevatorBlock // movingelevators:elevator_block)
	Actual block data value: 2 / 0x2 / 0b0010
Stacktrace:
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_192854_a(TileEntityRendererDispatcher.java:156)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:131)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:715)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1347)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259)

**Comment by SuperMartijn642** [comment]
The version you're using is from over a year ago.
Please update to the latest version of Moving Elevators, 1.2.34.
