### ISSUE TITLE
[Crash] when I start minecraft he crash

### ISSUE THREAD

**Issue by lucaandri007** [SuperMartijn642/MovingElevators#72]
**Version Info**
- Minecraft,1.17.1
- Moving Elevators,movingelevators-1.2.34a-mc1.17

**Steps to Reproduce**
have forge 37.0.65 with moving elevators and turn on

**Crash report (~/logs/latest.log)**

![Screenshot (33)](https://user-images.githubusercontent.com/92470109/137190446-91f93067-5297-4eab-bfee-99a8cf650615.png)

**Comment by lucaandri007** [comment]
this crash is on 37.0.88 forge

**Comment by lucaandri007** [comment]
and this is crash report:
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 8/29/21, 1:45 PM
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.fmllegacy.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:69) ~[forge-1.17.1-37.0.45-universal.jar%2359!:?] {re:classloading}
	at net.minecraftforge.fmlclient.ClientModLoader.completeModLoading(ClientModLoader.java:183) ~[forge-1.17.1-37.0.45-universal.jar%2359!:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$new$1(Minecraft.java:556) ~[client-1.17.1-20210706.113038-srg.jar%2355!:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.Util.m_137521_(Util.java:361) ~[client-1.17.1-20210706.113038-srg.jar%2355!:?] {re:classloading}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:550) ~[client-1.17.1-20210706.113038-srg.jar%2355!:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.LoadingOverlay.m_6305_(LoadingOverlay.java:135) ~[client-1.17.1-20210706.113038-srg.jar%2355!:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:874) ~[client-1.17.1-20210706.113038-srg.jar%2355!:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1040) ~[client-1.17.1-20210706.113038-srg.jar%2355!:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:660) ~[client-1.17.1-20210706.113038-srg.jar%2355!:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:186) ~[client-1.17.1-20210706.113038-srg.jar%2355!:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.17.1-37.0.45.jar%2321!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90) [bootstraplauncher-0.1.17.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-0.9.46.jar:?] {}
-- MOD movingelevators --
Details:
	Caused by 0: java.lang.NoClassDefFoundError: net/minecraftforge/common/ToolType
		at com.supermartijn642.movingelevators.base.MEBlock.<init>(MEBlock.java:45) ~[movingelevators-1.2.34a-mc1.17.jar%2354!:?] {re:classloading}
		at com.supermartijn642.movingelevators.base.ElevatorInputBlock.<init>(ElevatorInputBlock.java:20) ~[movingelevators-1.2.34a-mc1.17.jar%2354!:?] {re:classloading}
		at com.supermartijn642.movingelevators.ElevatorBlock.<init>(ElevatorBlock.java:31) ~[movingelevators-1.2.34a-mc1.17.jar%2354!:?] {re:classloading}
		at com.supermartijn642.movingelevators.MovingElevators$RegistryEvents.onBlockRegistry(MovingElevators.java:67) ~[movingelevators-1.2.34a-mc1.17.jar%2354!:?] {re:classloading}
		at net.minecraftforge.eventbus.ASMEventHandler_0_RegistryEvents_onBlockRegistry_Register.invoke(.dynamic) ~[?:?] {}
		at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!:?] {}
		at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!:?] {}
		at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[javafmllanguage-1.17.1-37.0.45.jar%2357!:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) ~[fmlcore-1.17.1-37.0.45.jar%2356!:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1800) ~[?:?] {}
		at net.minecraftforge.fml.ModWorkManager$SyncExecutor.driveOne(ModWorkManager.java:56) ~[fmlcore-1.17.1-37.0.45.jar%2356!:?] {}
		at net.minecraftforge.fml.ModWorkManager$DrivenExecutor.drive(ModWorkManager.java:40) ~[fmlcore-1.17.1-37.0.45.jar%2356!:?] {}
		at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:216) ~[fmlcore-1.17.1-37.0.45.jar%2356!:?] {}
		at net.minecraftforge.fml.ModLoader.lambda$dispatchAndHandleError$21(ModLoader.java:201) ~[fmlcore-1.17.1-37.0.45.jar%2356!:?] {}
		at java.util.Optional.ifPresent(Optional.java:178) ~[?:?] {}
		at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:201) ~[fmlcore-1.17.1-37.0.45.jar%2356!:?] {}
		at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$11(ModLoader.java:178) ~[fmlcore-1.17.1-37.0.45.jar%2356!:?] {}
		at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {}
		at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:178) ~[fmlcore-1.17.1-37.0.45.jar%2356!:?] {}
		at net.minecraftforge.fmlclient.ClientModLoader.lambda$begin$1(ClientModLoader.java:107) ~[forge-1.17.1-37.0.45-universal.jar%2359!:?] {re:classloading,pl:runtimedistcleaner:A}
		at net.minecraftforge.fmlclient.ClientModLoader.lambda$createRunnableWithCatch$4(ClientModLoader.java:127) ~[forge-1.17.1-37.0.45-universal.jar%2359!:?] {re:classloading,pl:runtimedistcleaner:A}
		at net.minecraftforge.fmlclient.ClientModLoader.begin(ClientModLoader.java:107) ~[forge-1.17.1-37.0.45-universal.jar%2359!:?] {re:classloading,pl:runtimedistcleaner:A}
		at net.minecraft.client.Minecraft.<init>(Minecraft.java:461) ~[client-1.17.1-20210706.113038-srg.jar%2355!:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
		at net.minecraft.client.main.Main.main(Main.java:151) ~[client-1.17.1-20210706.113038-srg.jar%2355!:?] {re:classloading,pl:runtimedistcleaner:A}
		at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
		at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?] {}
		at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
		at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?] {}
		at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.17.1-37.0.45.jar%2321!:?] {}
		at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.0.7.jar%235!:?] {}
		at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.0.7.jar%235!:?] {}
		at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.0.7.jar%235!:?] {}
		at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.0.7.jar%235!:?] {}
		at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.0.7.jar%235!:?] {}
		at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.0.7.jar%235!:?] {}
		at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.0.7.jar%235!:?] {}
		at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90) [bootstraplauncher-0.1.17.jar:?] {}

	Mod File: movingelevators-1.2.34a-mc1.17.jar
	Failure message: Moving Elevators (movingelevators) encountered an error during the common_setup event phase
		java.lang.NoClassDefFoundError: net/minecraftforge/common/ToolType
	Mod Version: 1.2.34a
	Mod Issue URL: NOT PROVIDED
	Exception message: java.lang.ClassNotFoundException: net.minecraftforge.common.ToolType
Stacktrace:
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-0.9.46.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?] {}
	at com.supermartijn642.movingelevators.base.MEBlock.<init>(MEBlock.java:45) ~[movingelevators-1.2.34a-mc1.17.jar%2354!:?] {re:classloading}
	at com.supermartijn642.movingelevators.base.ElevatorInputBlock.<init>(ElevatorInputBlock.java:20) ~[movingelevators-1.2.34a-mc1.17.jar%2354!:?] {re:classloading}
	at com.supermartijn642.movingelevators.ElevatorBlock.<init>(ElevatorBlock.java:31) ~[movingelevators-1.2.34a-mc1.17.jar%2354!:?] {re:classloading}
	at com.supermartijn642.movingelevators.MovingElevators$RegistryEvents.onBlockRegistry(MovingElevators.java:67) ~[movingelevators-1.2.34a-mc1.17.jar%2354!:?] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_0_RegistryEvents_onBlockRegistry_Register.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[javafmllanguage-1.17.1-37.0.45.jar%2357!:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) ~[fmlcore-1.17.1-37.0.45.jar%2356!:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1800) ~[?:?] {}
	at net.minecraftforge.fml.ModWorkManager$SyncExecutor.driveOne(ModWorkManager.java:56) ~[fmlcore-1.17.1-37.0.45.jar%2356!:?] {}
	at net.minecraftforge.fml.ModWorkManager$DrivenExecutor.drive(ModWorkManager.java:40) ~[fmlcore-1.17.1-37.0.45.jar%2356!:?] {}
	at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:216) ~[fmlcore-1.17.1-37.0.45.jar%2356!:?] {}
	at net.minecraftforge.fml.ModLoader.lambda$dispatchAndHandleError$21(ModLoader.java:201) ~[fmlcore-1.17.1-37.0.45.jar%2356!:?] {}
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?] {}
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:201) ~[fmlcore-1.17.1-37.0.45.jar%2356!:?] {}
	at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$11(ModLoader.java:178) ~[fmlcore-1.17.1-37.0.45.jar%2356!:?] {}
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {}
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:178) ~[fmlcore-1.17.1-37.0.45.jar%2356!:?] {}
	at net.minecraftforge.fmlclient.ClientModLoader.lambda$begin$1(ClientModLoader.java:107) ~[forge-1.17.1-37.0.45-universal.jar%2359!:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.fmlclient.ClientModLoader.lambda$createRunnableWithCatch$4(ClientModLoader.java:127) ~[forge-1.17.1-37.0.45-universal.jar%2359!:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.fmlclient.ClientModLoader.begin(ClientModLoader.java:107) ~[forge-1.17.1-37.0.45-universal.jar%2359!:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:461) ~[client-1.17.1-20210706.113038-srg.jar%2355!:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:151) ~[client-1.17.1-20210706.113038-srg.jar%2355!:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.17.1-37.0.45.jar%2321!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90) [bootstraplauncher-0.1.17.jar:?] {}


-- MOD movingelevators --
Details:
	Mod File: movingelevators-1.2.34a-mc1.17.jar
	Failure message: Moving Elevators (movingelevators) encountered an error during the error event phase
		java.lang.NullPointerException: null
	Mod Version: 1.2.34a
	Mod Issue URL: NOT PROVIDED
	Exception message: java.lang.NullPointerException
Stacktrace:
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770) ~[guava-21.0.jar%2319!:?] {}
	at com.google.common.collect.SingletonImmutableSet.<init>(SingletonImmutableSet.java:47) ~[guava-21.0.jar%2319!:?] {}
	at com.google.common.collect.ImmutableSet.of(ImmutableSet.java:82) ~[guava-21.0.jar%2319!:?] {}
	at com.google.common.collect.ImmutableSet.copyOf(ImmutableSet.java:319) ~[guava-21.0.jar%2319!:?] {}
	at net.minecraft.world.level.block.entity.BlockEntityType$Builder.m_155273_(BlockEntityType.java:119) ~[client-1.17.1-20210706.113038-srg.jar%2355!:?] {re:classloading}
	at com.supermartijn642.movingelevators.MovingElevators$RegistryEvents.onTileRegistry(MovingElevators.java:74) ~[movingelevators-1.2.34a-mc1.17.jar%2354!:?] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_1_RegistryEvents_onTileRegistry_Register.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[javafmllanguage-1.17.1-37.0.45.jar%2357!:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) ~[fmlcore-1.17.1-37.0.45.jar%2356!:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1800) ~[?:?] {}
	at net.minecraftforge.fml.ModWorkManager$SyncExecutor.driveOne(ModWorkManager.java:56) ~[fmlcore-1.17.1-37.0.45.jar%2356!:?] {}
	at net.minecraftforge.fml.ModWorkManager$DrivenExecutor.drive(ModWorkManager.java:40) ~[fmlcore-1.17.1-37.0.45.jar%2356!:?] {}
	at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:216) ~[fmlcore-1.17.1-37.0.45.jar%2356!:?] {}
	at net.minecraftforge.fml.ModLoader.lambda$dispatchAndHandleError$21(ModLoader.java:201) ~[fmlcore-1.17.1-37.0.45.jar%2356!:?] {}
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?] {}
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:201) ~[fmlcore-1.17.1-37.0.45.jar%2356!:?] {}
	at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$11(ModLoader.java:178) ~[fmlcore-1.17.1-37.0.45.jar%2356!:?] {}
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {}
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:178) ~[fmlcore-1.17.1-37.0.45.jar%2356!:?] {}
	at net.minecraftforge.fmlclient.ClientModLoader.lambda$begin$1(ClientModLoader.java:107) ~[forge-1.17.1-37.0.45-universal.jar%2359!:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.fmlclient.ClientModLoader.lambda$createRunnableWithCatch$4(ClientModLoader.java:127) ~[forge-1.17.1-37.0.45-universal.jar%2359!:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.fmlclient.ClientModLoader.begin(ClientModLoader.java:107) ~[forge-1.17.1-37.0.45-universal.jar%2359!:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:461) ~[client-1.17.1-20210706.113038-srg.jar%2355!:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:151) ~[client-1.17.1-20210706.113038-srg.jar%2355!:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.17.1-37.0.45.jar%2321!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90) [bootstraplauncher-0.1.17.jar:?] {}


-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 624705920 bytes (595 MiB) / 1711276032 bytes (1632 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 2
	Microarchitecture: unknown
	Frequency (GHz): 2.50
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce GTX 1660 Ti
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2191
	Graphics card #0 versionInfo: DriverVersion=27.21.14.5749
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.93
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.93
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 18723.80
	Virtual memory used (MB): 14307.64
	Swap memory total (MB): 2432.00
	Swap memory used (MB): 155.23
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 9.0.7+91+master.8569cdf
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 eventbus PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_inject_definalize PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
	Mod List: 
		client-1.17.1-20210706.113038-srg.jar             |Minecraft                     |minecraft                     |1.17.1              |COMMON_SET|Manifest: NOSIGNATURE
		movingelevators-1.2.34a-mc1.17.jar                |Moving Elevators              |movingelevators               |1.2.34a             |ERROR     |Manifest: NOSIGNATURE
		forge-1.17.1-37.0.45-universal.jar                |Forge                         |forge                         |37.0.45             |COMMON_SET|Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		cfm-7.0.0-pre24-mc1.17.1.jar                      |MrCrayfish's Furniture Mod    |cfm                           |7.0.0-pre24         |COMMON_SET|Manifest: NOSIGNATURE
		journeymap-1.17.1-5.7.3rc3.jar                    |Journeymap                    |journeymap                    |5.7.3rc3            |COMMON_SET|Manifest: NOSIGNATURE
	Crash Report UUID: 6ddf4dab-146a-4193-8173-579856263efc
	FML: 37.0
	Forge: net.minecraftforge:37.0.45

**Comment by SuperMartijn642** [comment]
Same as #70.

Forge 37.0.31 had a breaking change. I am in the midst of a large update for Moving Elevators, thus I haven't been able to update it for the newer Forge versions.
For now, you can either use Forge 37.0.30 or lower, or wait for the update 🙂 (although the update might take a bit)

**Comment by lucaandri007** [comment]
yeah i know but he still crash

**Comment by lucaandri007** [comment]
yes I knew that's why I changed but it still doesn't work

**Comment by lucaandri007** [comment]
no he doesnt work.:((

**Comment by SuperMartijn642** [comment]
You've used Forge 37.0.88, 37.0.65, and 37.0.45. None of those are below 37.0.31.

**Comment by lucaandri007** [comment]
I'm stupid I forgot to change the forge

**Comment by lucaandri007** [comment]
thnk you very much creator!

**Comment by MarvellJayden1205** [comment]
I use Forge 37.0.30, it crashed so i use Forge 37.0.31
