### ISSUE TITLE
[Crash] of your Mod for 1.12.2 in the newest 1.3.1 Version

### ISSUE THREAD

**Issue by Titoo8899** [SuperMartijn642/MovingElevators#95]
**Version Info**
Minecraft Forge Version Tester on forge-1.12.2-14.23.5.2855, forge-1.12.2-14.23.5.2856 and forge-1.12.2-14.23.5.2860
Moving Elevator Mod Version 1.3.1

**Steps to Reproduce**

Only make by JVM-Argument 
-Xmx10G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M

and then load the mods and by load of the first steps crash the game

Crash Report

---- Minecraft Crash Report ----

WARNING: coremods are present:
  SuperMartijn642's Core Lib Plugin (supermartijn642corelib-1.0.16a-mc1.12.jar)
Contact their authors BEFORE contacting forge

// Don't do that.

Time: 2/18/22 6:10 PM
Description: Initializing game

java.lang.NullPointerException: Initializing game
	at com.supermartijn642.movingelevators.MovingElevatorsClient.setup(MovingElevatorsClient.java:50)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_8_MovingElevatorsClient_setup_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:845)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:630)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.supermartijn642.movingelevators.MovingElevatorsClient.setup(MovingElevatorsClient.java:50)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_8_MovingElevatorsClient_setup_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:845)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:630)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 635092040 bytes (605 MB) / 1073741824 bytes (1024 MB) up to 10737418240 bytes (10240 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx10G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2855 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                       | Version      | Source                                    | Signature                                |
	|:----- |:------------------------ |:------------ |:----------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft                | 1.12.2       | minecraft.jar                             | None                                     |
	| LCH   | mcp                      | 9.42         | minecraft.jar                             | None                                     |
	| LCH   | FML                      | 8.0.99.99    | forge-1.12.2-14.23.5.2855.jar             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge                    | 14.23.5.2855 | forge-1.12.2-14.23.5.2855.jar             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | supermartijn642configlib | 1.0.9        | supermartijn642configlib-1.0.9-mc1.12.jar | None                                     |
	| LCH   | supermartijn642corelib   | 1.0.16a      | supermartijn642corelib-1.0.16a-mc1.12.jar | None                                     |
	| LCH   | movingelevators          | 1.3.1        | movingelevators-1.3.1-mc1.12.jar          | None                                     |

	Loaded coremods (and transformers): 
SuperMartijn642's Core Lib Plugin (supermartijn642corelib-1.0.16a-mc1.12.jar)
  
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 511.79' Renderer: 'NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2'
	Launched Version: 1.12.2-forge-14.23.5.2855
	LWJGL: 2.9.4
	OpenGL: NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 511.79, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 6x Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz

**Comment by c-harlotte** [comment]
https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-core-lib
https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-config-lib

I downloaded those two and it started working for me

**Comment by Titoo8899** [comment]
C-harlotte I have this 2 mods in my mod folder look in the crash report. In this was all Mods and other thinks what in this moment load

**Comment by c-harlotte** [comment]
oh alright my bad, i didnt read the crash report

**Comment by SuperMartijn642** [comment]
I fixed the issue now in Moving Elevators 1.3.2.

Thank you for reporting the issue!
